### ISSUE TITLE
Replace Queue System

### ISSUE THREAD

**Issue by kevyonan** [Starblaster64/Vs-Saxton-Hale-2#124]
Global queue array that's updated whenever a player leaves/connects or changes teams.

```c
enum struct Queue {
    BaseBoss players[PLYR];
    int len;
}
```

**Comment by Scags** [comment]
Good idea. If possible, could there be a method where players who join late receive a "grace period"? Where, if they are supposed to be a boss immediately when they join, their boss conversion is delayed to the next round over? I've gotten people complain about being a boss immediately when they join but I've never thought of a solid method to bypass it.

Edit: I'm thinking that the player_connect event could be used here; since OnClientPutInServer/OnClientConnected fires whenever the map changes, whereas the event only fires once per client per connection. Secondly, wouldn't an ArrayList (or an ArrayQueue wrapper methodmap) fit the bill here? Would make more sense considering the queue length is dynamic.

**Comment by kevyonan** [comment]
@Scags you're right but a straight up array will have better performance over the `ArrayList` accessing because of all the steps that Handles have to go through compared to a regular array.
Besides, using the `len` field, we can update it like dynamic as needed.
