### ISSUE TITLE
Mantreads negate fall damage attribute redundant

### ISSUE THREAD

**Issue by Starblaster64** [Starblaster64/Vs-Saxton-Hale-2#14]
Why does the Mantreads even have the cancel falling damage attribute when all fall damage is disabled anyway?

**Comment by assyrianic** [comment]
purpose of it to make it as attractive an alternative to the gunboats.

with gunboats, you take fall damage despite having a lower initial rocket jump damage.

with mantreads, you take normal rocket jump damage but you fly higher and you don't need to worry about fall damage.

Are you saying the VSH2 mod itself disables fall damage? If so that's highly unintentional.

**Comment by Starblaster64** [comment]
Yes, that's exactly what I'm saying. Unless I've gone an broken something so much that fall damage is disabled on my test server.

**Comment by Starblaster64** [comment]
Also, I'd recommend switching to how VSH handles boots fall damage for the Mantreads, instead of the attribute so you can still handle Mantread stomps for non-Bosses.

**Comment by assyrianic** [comment]
the only I didn't include the mantreads stomp thing was on account that the majority of VSH/FF2 servers utilize the goomba stomp plugin.

**Comment by Starblaster64** [comment]
Closing this in favour of a new issue for the no fall-damage bug.
