### ISSUE TITLE
[ConfigMap] Set and ExportToFile don't work properly

### ISSUE THREAD

**Issue by MAGNAT2645** [Starblaster64/Vs-Saxton-Hale-2#221]
`ConfigMap.Set` and `ConfigMap.ExportToFile` don't work as they should.

Here's the code to test:
```sourcepawn
public void OnPluginStart()
{
    ConfigMap hConfig = new ConfigMap( "configs/aon/test_cfgmap.cfg" );
    if ( !hConfig.Set( "root.section1.key1", "TEST 1" ) )
        PrintToServer( "Couldn't set key1!" );

    ConfigMap hSection1 = hConfig.GetSection( "root.section1" );
    if ( !hSection1.Set( "key2", "TEST 2" ) )
        PrintToServer( "Couldn't set key2!" );

    char szBuffer[32];
    hConfig.Get( "root.section1.key3", szBuffer, sizeof szBuffer );
    PrintToServer( "key3 is \"%s\"", szBuffer );

    if ( !hSection1.Set( "key3", "TRULY 3" ) )
        PrintToServer( "Couldn't set key3!" );

    hConfig.Get( "root.section1.key3", szBuffer, sizeof szBuffer );
    PrintToServer( "now key3 is \"%s\"", szBuffer );

    PrintCfg( hConfig );

    if ( !hConfig.ExportToFile( "section2", "configs/aon/test_cfgmap_exported.cfg" ) )
        PrintToServer( "Couldn't export!" );

    DeleteCfg( hConfig );
}
```

Here's the config:
```
"root"
{
    "section1"
    {
        "key3"  "TEST 3"
    }
}
```

Console output:
```
Couldn't set key1!
Couldn't set key2!
key3 is "TEST 3"
now key3 is "TRULY 3"
ConfigMap ::            key: 'root', Section
ConfigMap ::            key: 'section1', Section
ConfigMap :: key: 'key3', val.size: '8'
Couldn't export!
```

It seems that `Set` only works with already existing keys.

**Comment by JassJam** [comment]
`ConfigMap.ExportToFile` takes a relative path to the game's directory, you should instead use `BuildPath` to resolve that.

> It seems that `Set` only works with already existing keys.

That's by design, if you really want to set an non existent key, refer to [ConfigMapAllocator](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/modules/ff2/backwards_compatibility.sp#L12) to see how it's implemented.

- `ConfigMapAllocator.NewValue` is to allocate a value directly to a path, and doesn't care about dots for sub-sections.

- `ConfigMapAllocator.NewSection` is the same as `NewValue` but for sections.

- `ConfigMapAllocator.ReserveNewValues` ensure that there is a section and contains an empty value in that path, it's useful if you're unsure about the existence of a path, and unlike `NewValue`, this one can handle sub-sections.

- `ConfigMapAllocator.ReserveNewSection` is the same as `ReserveNewValues` but for sections, note that the `enumeration` parameter should be set to >= 1 if the value / sections are an array.

 
 The reason behind why it's kept hidden from the public `ConfigMap`, is that i's too much to handle for a single include and should not be used unless it's necessary. (FF2 uses it to convert old configs to a new config [freaks/vsh2ff2_sample.cfg](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/freaks/vsh2ff2_sample.cfg)).


The example below shows how you can achieve the results.
```SourcePawn

public void OnPluginStart()
{
    ConfigMap hConfig = new ConfigMap( "configs/aon/test_cfgmap.cfg" );
    ConfigMapAllocator root_config = ConfigMapAllocator(hConfig);

    /// Reserve a value after we check it doesn't exists from the root
    if ( !hConfig.Set( "root.section1.key1", "TEST 1" ) ) {
        root_config.ReserveNewValues("root.section1.key1");
        hConfig.Set("root.section1.key1", "TEST 1");
    }

    /// Check if the value doesn't exist, then allocate a new one directly if that's the case
    ConfigMap hSection1 = hConfig.GetSection( "root.section1" );
    ConfigMapAllocator section1 = ConfigMapAllocator(hSection1);
    if ( !hSection1.Set( "key2", "TEST 2" ) ) {
        /// str = "TEST 2"
        /// str's size = sizeof(str) (6 characters + null terminator)
        section1.NewValue("key2", "TEST 2", strlen("TEST 2") + 1);
    }

    char szBuffer[32];
    hConfig.Get( "root.section1.key3", szBuffer, sizeof(szBuffer));
    PrintToServer( "key3 is \"%s\"", szBuffer );

    /// Reserve a value to ensure it's existence, then set it
    section1.ReserveNewValues("key3");
    if ( !hSection1.Set( "key3", "TRULY 3" ) )
        PrintToServer( "Couldn't set key3!" );

    hConfig.Get( "root.section1.key3", szBuffer, sizeof(szBuffer));
    PrintToServer( "now key3 is \"%s\"", szBuffer );

    PrintCfg( hConfig );

    char path[PLATFORM_MAX_PATH]
    BuildPath(Path_SM, path, sizeof(path), "configs/aon/test_cfgmap_exported.cfg");
    if ( !hConfig.ExportToFile( "section2", path ) )
        PrintToServer( "Couldn't export!" );

    DeleteCfg( hConfig );
}
```

**Comment by MAGNAT2645** [comment]
Didn't know about `ConfigMapAllocator` and forgot about `BuildPath` :smile:
