### ISSUE TITLE
Bosses and Red players picking up each other's weapons

### ISSUE THREAD

**Issue by assyrianic** [Starblaster64/Vs-Saxton-Hale-2#38]
should probably block this as well and I do not know how to block this.

**Comment by Starblaster64** [comment]
I do, but it's a bit of a hacky fix, I used it in my fork of VSH1. 

First, I delete any `tf_dropped_weapon` entity that belongs to the Boss's team so that the non-Bosses don't get a chance to pick them up. 

Second, I set the Prop_Data `m_bPreventWeaponPickup` to `true` on the Boss at the start of the round. While it sounds like it prevents them from picking up weapons at all, Valve made it behave really weirdly. The Boss will still be able to pick weapons, but they'll be destroyed instantly, leaving an empty weapon slot behind. 

To solve this issue, I have the Boss be re-equipped if they have an invalid main weapon, which most of the time will be their Melee slot (This is the really 'hacky' part of the fix). If they have an invalid non-main weapon (like the CBS's bow), I set it to force weapon switch back to their main weapon (e.g. Melee).

The last thing to note with this method is the `m_bPreventWeaponPickup` sticks around even after death, so I have to set it to `false` on all non-bosses at the end of the round/start of the next round (I added a few redundancies just in-case).

**Comment by Starblaster64** [comment]
Alternatively we could do what everyone else did and just disable weapon drops entirely p:

**Comment by assyrianic** [comment]
yes, disable weapon drops then. Maybe put a cvar for it incase some servers implement dropped weapons as a server gimmick?

**Comment by Starblaster64** [comment]
Ok, well there are two ways to block the drops. We can either destroy any dropped weapon entities as they are created and toggle it with a CVAR. Or, we can create a VSH2 CVAR to control the already existing hidden CVAR that controls dropped weapon lifetime.
I'm thinking the entity method is probably better for us since toggling CVARs with CVARs seems a bit convoluted.

**Comment by assyrianic** [comment]
yes, the entity method i approve
