### ISSUE TITLE
have shields regenerate after doing a certain amount of damage

### ISSUE THREAD

**Issue by kevyonan** [Starblaster64/Vs-Saxton-Hale-2#62]

**Comment by Starblaster64** [comment]
Might as well toss this idea here, since it's related.

**Suggestion:** Move Shield hit blocking from the Shields, to the Eyelander.
**Explanation:** Basically instead of shields just giving a free block, move it to the Eyelander's heads. Set some threshold (and a CVAR) like 3 heads required to block a _(only fatal hits maybe?)_ hit. Also include some sort of visual indicator above or on the Demoman to show he is able to tank a hit. _(I used marked for death in my version of VSH1, which also increased the amount of HP needed for a non-fatal hit. I did this intentionally for balance reasons.)_

This _would_ make it harder for Demomen to initially be able to tank a hit, but it means that:
**1.**  You get to keep your shield even after blocking a hit.
**2.** Players can use Stickybombs while still having the opportunity to block a hit.
**3.** It actually requires some effort to block a hit, instead of for free simply by equipping an item.

**Comment by kevyonan** [comment]
Thing is, demoman deserves the free 1st hit block because he's sacrificing a secondary weapon in which he's pretty much nerfing himself. We have the give the player some kind of reward/compensation for nerfing themselves like this.

Secondly, we want to keep the gameplay as simple as possible. It makes more sense just to have the shields take a hit exclusively for the Demo-knight subclass.

Also, don't forget that most of the players are preteens and teenagers, we need to have the right mix of easy yet hard so there's at least some semblance of challenge which is why I'm opting for having shields regen after doing a certain amount of damage.

It also probably wouldn't hurt if I gave Demo a hud letting them know if their shield is active or gone.

**Comment by Starblaster64** [comment]
I find it interesting you consider equipping a shield as a nerf.
By equipping a shield you get more damage (crits/minicrits, depending on the CVAR value) on your grenade launcher, and an on-demand escape mechanism that doesn't sacrifice any HP. In addition to all that, you also get to survive a hit for free.

The sticky bomb launcher may be more powerful in terms of potential damage output, but the shield is definitely easier to get more damage with in direct combat, in my opinion.

I agree with the "simple as possible" philosophy though, and shields do seem like something that might block a hit visually speaking, even if I may disagree on the mechanic itself.

Ultimately I guess it doesn't hurt to add more features anyway, since you're adding a CVAR for this regardless.

**Comment by kevyonan** [comment]
alright, I'm setting up the code for the whole regen setup but one last question is: do I regenerate/give them a basic charge 'n targe or give them the shield they originally spawned with but that would require recording their spawning data?

**Comment by Starblaster64** [comment]
I would highly recommend trying to spawn same shield they started with.
Would it be possible to just hide the shield model when it "breaks" and then kind of freeze the charge meter until you regen it?

EDIT: actually it would still show in the viewmodel regardless so hm.

I would record their shield type when it gets destroyed, not on spawn. That way it can account for class changes/regens mid-round from other stuff.

**Comment by kevyonan** [comment]
ok so I got it all working! Problem is that I had to go "ghetto" by using ugly code to get it working BUT it works. No errors generated or anything.

here's the code so far
```c++
	if( !attacker.bHasShield ) {
		int iReqDmg = cvarVSH2[ShieldRegenDmgReq].IntValue;
		if( iReqDmg>0 ) {
			attacker.iShieldDmg += damage;
			if( attacker.iShieldDmg >= iReqDmg ) {
				// save data so we can get our shield back.
				// save health, heads, and weapon data.
				int client = attacker.index;
				int health, heads, primclip, primammo;
				health = GetClientHealth(client);
				if( HasEntProp(client, Prop_Send, "m_iDecapitations") )
					heads = GetEntProp(client, Prop_Send, "m_iDecapitations");
				primammo = GetAmmo(client, TFWeaponSlot_Primary);
				primclip = GetClip(client, TFWeaponSlot_Primary);
				
				// "respawn" player.
				TF2_RegeneratePlayer(client);
				// reset old data
				SetEntityHealth(client, health);
				if( HasEntProp(client, Prop_Send, "m_iDecapitations") and heads>0 )
					SetEntProp(client, Prop_Send, "m_iDecapitations", heads);
				SetAmmo(client, TFWeaponSlot_Primary, primammo);
				SetClip(client, TFWeaponSlot_Primary, primclip);
				attacker.iShieldDmg = 0;
				attacker.bHasShield = true;
			}
		}
	}
```

**Comment by Starblaster64** [comment]
Is bHasShield checking m_bShieldEquipped? Or is it just an additional var?
You should be able to just check GetEntProp(i, Prop_Send, "m_bShieldEquipped"), no need to set it to true or false, it's handled automatically by the game.

**Comment by kevyonan** [comment]
oooo, let me try that! EDIT: Yep, works fine. removed `bHasShield`

**Comment by kevyonan** [comment]
alright, here's updated code.
```c++
	if( !GetEntProp(attacker.index, Prop_Send, "m_bShieldEquipped") ) {
		int iReqDmg = cvarVSH2[ShieldRegenDmgReq].IntValue;
		if( iReqDmg>0 ) {
			attacker.iShieldDmg += damage;
			if( attacker.iShieldDmg >= iReqDmg ) {
				// save data so we can get our shield back.
				// save health, heads, and weapon data.
				int client = attacker.index;
				int health, heads, primclip, primammo;
				health = GetClientHealth(client);
				if( HasEntProp(client, Prop_Send, "m_iDecapitations") )
					heads = GetEntProp(client, Prop_Send, "m_iDecapitations");
				primammo = GetAmmo(client, TFWeaponSlot_Primary);
				primclip = GetClip(client, TFWeaponSlot_Primary);
				
				// "respawn" player.
				TF2_RegeneratePlayer(client);
				// reset old data
				SetEntityHealth(client, health);
				if( HasEntProp(client, Prop_Send, "m_iDecapitations") and heads>0 )
					SetEntProp(client, Prop_Send, "m_iDecapitations", heads);
				SetAmmo(client, TFWeaponSlot_Primary, primammo);
				SetClip(client, TFWeaponSlot_Primary, primclip);
				attacker.iShieldDmg = 0;
			}
		}
	}
```

**Comment by kevyonan** [comment]
update implemented!
