### ISSUE TITLE
[Docs] Modifying health formula?

### ISSUE THREAD

**Issue by GIANTCRAB** [Starblaster64/Vs-Saxton-Hale-2#67]
Hey, thanks for the rewrite of the system and the contribution! 

I'm currently trying to write a boss script but I couldn't find documentation on modifying the boss's health formula. Is there a way to do so? 

PS: If you have time, could you try to let me know how do I do an explosive dance code in the new system? (Having a hard time figuring this out as well)

Thanks!

**Comment by kevyonan** [comment]
boss health formula is handled automatically but you can manually set it anytime.
Boss health is set as soon as the Arena round starts. As for the health formula, it's based on a function called `CalcBossHealth`

Here's the full formula used in the code...
You can find this snippet in [events.sp](https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/blob/develop/addons/sourcemod/scripting/modules/events.sp#L398)
```cpp
boss.iMaxHealth = CalcBossHealth(760.8, gamemode.iPlaying, 1.0, 1.0341, 2046.0) / (bosscount);	// In stocks.sp`
```

here's the stock function
```cpp
stock int CalcBossHealth(const float initial, const int playing, const float subtract, const float exponent, const float additional)
{
	return RoundFloat( Pow((((initial)+playing)*(playing-subtract)), exponent)+additional );
}
```

Probably, the best time to modify boss health is `ManageMessageIntro` in handler.sp since it's called AFTER setting up boss health.

**Comment by kevyonan** [comment]
there, I made a page on the wiki how to override boss health post-calculation. https://github.com/VSH2-Devs/Vs-Saxton-Hale-2/wiki/Modifying-Overriding-Boss-Health
